version: "3.8"

services:
  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "5088:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      # Hosts permitidos para Django (sin puerto). Ajusta seg√∫n tu IP/dominios.
      - DJANGO_ALLOWED_HOSTS=sen.yvagacore.com,161.35.53.140

  frontend:
    build:
      context: ../BA-SEN-Front
    container_name: frontend
    ports:
      - "3227:80"
    depends_on:
      - backend
